routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
//    Artisan::call('storage:link');
    return view('home');
})->name('home');


Route::get('/part', function () {
    return view('frontend.image-parts');
})->name('part');

Route::get('/test', function () {
    return view('chin-correction.test');
})->name('test');



Route::post('before-register', 'Auth\RegisterController@before_register');

Route::post('login', 'Auth\LoginController@login');

Route::group(['middleware' => 'auth'], function () {
    Route::get('/dashboard', function () {
        return view('frontend.dashboard');
    })->name('dashboard');
});


/* Admin Route*/

Route::group(['prefix' => 'admin'], function () {
    Voyager::routes();
    Route::post('answer-change-service', 'AnswerController@change_service')->name('answer.change_service');
    Route::post('answer-store', 'AnswerController@store')->name('voyager.answers.store');
    Route::put('answer-update/{id}', 'AnswerController@update')->name('voyager.answers.update');
});


//

/*UPLOAD ROUTE*/
Route::post('upload', 'MediaController@upload')->name('upload'); // Upload image

Route::post('crop/{service}/{type}', 'MediaController@crop')->name('crop'); // Crop image

Route::delete('delete-image', 'MediaController@destroy')->name('delete-image'); // delete image




Route::group(['middleware' => 'save-data'], function () {
   Route::get('save-date', 'ServiceController@save_data')->name('save_data');
});
Route::group(['middleware' => ['verified','block']], function () {
    /* PROFILE ROUTE */
    Route::resource('profile', 'ProfileController');
    Route::get('profile/service/{service?}/{test_id?}', 'ProfileController@index')->name('profile.service');
    Route::get('profile-verification', 'ProfileController@verification')->name('profile.verification');
    Route::get('resend-email', 'Auth\AuthController@resend')->name('email.resend-email');
    Route::post('change-resend-email', 'Auth\AuthController@change_resend')->name('email.change-resend-email');

});


Route::get('/auth/{id}/{token}', 'Auth\AuthController@check_token')->name('check-token');


/*SERVICES ROUTE*/
Route::group(['prefix' => 'services'], function () {

    Route::get('', 'ServiceController@index')->name('services');
    Route::get('{service}', 'ServiceController@service')->name('services.service');
    Route::get('{service}/{type}/{test_id?}', 'ServiceController@type')->name('service.type');
    Route::put('{service}/{type}/add-data/{test_id?}', 'ServiceController@add_data')->name('service.add_data');
});



Auth::routes();
Auth::routes(['verify' => true]);

Route::get('/home', function (){
    return redirect()->route('home');
});

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <title>AM|PERFECT</title>
    <!--======= META =======-->
    <meta charset="UTF-8"/>
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0"/>
    <meta http-equiv="X-UA-Compatible" content="ie=edge"/>
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <!--======= GOOGLE FONTS ========-->
    <link href="https://fonts.googleapis.com/css?family=Tangerine" rel="stylesheet">


    <!--======= ICON ========-->
    <link rel="icon" href="{{ asset('storage/img/logo.png') }}" type="image/x-icon">
    <!--======= FONT GOOGLE ========-->
    <link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet">

    <!--======= FONT AWESOME ========-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css"
          integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
    <!--======= BOOTSTRAP ========-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css"
          integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B" crossorigin="anonymous"/>
    <link rel="stylesheet" href="{{ asset('css/et-line.css') }}"/>
    <!--======= ION ICONS =======-->
    <link href="https://unpkg.com/ionicons@4.3.0/dist/css/ionicons.min.css" rel="stylesheet">

    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" rel="stylesheet">

    <!--======= OWN CSS =======-->
    @yield('style')
    <link rel="stylesheet" href="{{ asset('css/style.css') }}"/>
    <link rel="stylesheet" href="{{ asset('css/media.css') }}"/>
</head>
<body>

@yield('content')

@guest
    <!-- =================== LOGIN MODAL ======================= -->
    @include('partials.login-modal')
@endguest

<!--======= SCRIPTS =======-->

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<!--======= BOOTSTRAP =======-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js"
        integrity="sha384-o+RDsa0aLu++PJvFqy8fFScvbHFLtbvScb8AjopnFD+iEQ7wo/CG0xlczd+2O/em"
        crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>

<!--======= OWN JS =======-->
{{--@section("smoot")--}}
{{--<script src="{{ asset('js/smoothScroll.js') }}"></script>--}}
{{--@show--}}
<script>
    @if(session('message'))

    /* TODO: change Controllers to use AlertsMessages trait... then remove this*/
    var alertType = <?php echo json_encode(Session::get('alert-type', 'info')); ?>;
    var alertMessage = <?php echo json_encode(Session::get('message')); ?>;
    var alerter = toastr[alertType];

    if (alerter) {
        alerter(alertMessage);
    } else {
        toastr.error("toastr alert-type " + alertType + " is unknown");
    }

    @endif
    @if (count($errors) > 0)
    @foreach ($errors->all() as $error)
    toastr.error("{{$error}}");
    @endforeach
    @endif
</script>

@if(Request::url() == route('home'))
    <script>
        $('html,body').smoothScroll();
        underHeader = $('.under__header').offset().top;
        headerSocIcons = $('.navbar__menu').offset().top;
        headerSocIconsHeight = $('.navbar__menu').height();
        $(window).scroll(function () {
            if ($(window).width() > 567) {
                if ($(window).scrollTop() >= underHeader) {
                    $('.under__header').addClass('fixed__header')
                } else {
                    $('.under__header').removeClass('fixed__header')
                }
            } else {
                if ($(window).scrollTop() >= headerSocIcons + headerSocIconsHeight) {
                    $('.under__header').addClass('fixed__header')
                } else {
                    $('.under__header').removeClass('fixed__header')
                }
            }

        })
    </script>
@else
    <script src="{{ asset('js/init.js') }}"></script>
@endif
<script> var test_form = false; </script>
@yield('script')
<script src="{{ asset('js/custom.js') }}"></script>
</body>
</html>

resources/views/layouts/navbar.blade.php
@if(Route::current()->getName() == 'home')
    <nav class="navbar__menu">
        <ul class="d-flex d-md-block justify-content-around">
            <li class="navbar__items"><a href="">about</a></li>
            <li class="navbar__items"><a href="{{ route('services') }}">services</a></li>
            <li class="navbar__items"><a href="">tutorials</a></li>
            <li class="navbar__items"><a href="">partnership</a></li>
            <li class="navbar__items"><a href="">professionals</a></li>
        </ul>
    </nav>
@else
    <nav class="navbar__menu">
        <ul class="d-flex  justify-content-center">
            <li class="navbar__items mr-md-2 mr-1"><a href="">about</a></li>
            <li class="navbar__items mr-md-2 mr-1"><a href="{{ route('services') }}">services</a></li>
            <li class="navbar__items mr-md-2 mr-1"><a href="">tutorials</a></li>
            <li class="navbar__items mr-md-2 mr-1"><a href="">partnership</a></li>
            <li class="navbar__items mr-md-2 mr-1"><a href="">professionals</a></li>
        </ul>
        @if(Auth::check())
            <ul class="d-flex mr-auto justify-content-center">
                <li class="navbar__items mr-md-2 mr-1">
                    <a href="{{route('profile.index')}}">Profile</a>
                </li>
                <li class="navbar__items mr-md-2 mr-1">
                    <a href="{{ route('logout') }}" onclick="event.preventDefault();document.getElementById('logout-form').submit();">Logout</a>
                </li>
                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                    @csrf
                </form>
            </ul>
        @else
            <ul class="d-flex mr-auto justify-content-center">
                <li class="navbar__items mr-md-2 mr-1"><a href="" data-toggle="modal" data-target="#modal-login">Login</a>
                </li>
                {{--<li class="navbar__items mr-md-2 mr-1"><a href="{{ route('register') }}">register</a></li>--}}
            </ul>
        @endif
    </nav>
@endif

resources/views/layouts/reg.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <title>AMLPERFECT</title>
    <!--======= META =======-->
    <meta charset="UTF-8"/>
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0"/>
    <meta http-equiv="X-UA-Compatible" content="ie=edge"/>
    <!--======= GOOGLE FONTS ========-->
    <link href="https://fonts.googleapis.com/css?family=Tangerine" rel="stylesheet">


    <!--======= ICON ========-->
    <link rel="icon" href="{{ asset('storage/img/logo.png') }}" type="image/x-icon">
    <!--======= FONT GOOGLE ========-->
    <link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet">

    <!--======= FONT AWESOME ========-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css"
          integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
    <!--======= BOOTSTRAP ========-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css"
          integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B" crossorigin="anonymous"/>
    <link rel="stylesheet" href="{{ asset('css/et-line.css') }}"/>
    <!--======= ION ICONS =======-->
    <link href="https://unpkg.com/ionicons@4.3.0/dist/css/ionicons.min.css" rel="stylesheet">

    <!--======= OWN CSS =======-->
    <link rel="stylesheet" href="{{ asset('css/style.css') }}"/>
    <link rel="stylesheet" href="{{ asset('css/media.css') }}"/>
    <!--======= MODERNISER =======-->
    <link rel="stylesheet" href="{{ asset('js/modernizr.custom.js') }}"/>
</head>
<body>

    @yield('content')

    <!--======= SCRIPTS =======-->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <!--======= BOOTSTRAP =======-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
            integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js"
            integrity="sha384-o+RDsa0aLu++PJvFqy8fFScvbHFLtbvScb8AjopnFD+iEQ7wo/CG0xlczd+2O/em"
            crossorigin="anonymous"></script>

    <!--======= OWN JS =======-->
    <script src="{{ asset('js/smoothScroll.js') }}"></script>
    <script src="{{ asset('js/init.js') }}"></script>
    <script src="{{ asset('js/classie.js') }}"></script>
    <script src="{{ asset('js/svgcheckbx.js') }}"></script>
    <script>
        (function() {
            // trim polyfill : https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/Trim
            if (!String.prototype.trim) {
                (function() {
                    // Make sure we trim BOM and NBSP
                    var rtrim = /^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g;
                    String.prototype.trim = function() {
                        return this.replace(rtrim, '');
                    };
                })();
            }

            [].slice.call( document.querySelectorAll( 'input.input__field' ) ).forEach( function( inputEl ) {
                // in case the input is already filled..
                if( inputEl.value.trim() !== '' ) {
                    classie.add( inputEl.parentNode, 'input--filled' );
                }

                // events:
                inputEl.addEventListener( 'focus', onInputFocus );
                inputEl.addEventListener( 'blur', onInputBlur );
            } );

            function onInputFocus( ev ) {
                classie.add( ev.target.parentNode, 'input--filled' );
            }

            function onInputBlur( ev ) {
                if( ev.target.value.trim() === '' ) {
                    classie.remove( ev.target.parentNode, 'input--filled' );
                }
            }
        })();
    </script>
</body>
</html>

resources/views/layouts/search.blade.php
<div class="row justify-content-end align-items-center px-3 text-md-right order-2">
    <div class="header__search__bar col-md-8 hidden-xs d-none d-md-block">
        <form action="">
            <input type="search" name="search" class="border-0"
                   placeholder="search for procedure and professionals">
            <button class="bg-transparent border-0"><i class="fas fa-search"></i></button>
        </form>
    </div>
    <div class="header__soc__icons col-md-4 text-right ">
        <a href="" class="mr-2"><i class="far fa-envelope"></i></a>
        <a href="" class="mr-2"><i class="icon ion-logo-youtube"></i></a>
        <a href="" class="mr-2"><i class="fab fa-facebook-f"></i></a>
        <a href="" class="mr-2"><i class="fab fa-instagram"></i></a>
    </div>
</div>